### ISSUE TITLE
IPC/FBP EMP/Damage Resistance

### ISSUE THREAD

**Issue by andersonconagher** [scrdest/UristMcStation#50]
Sorry if this is the wrong place to post, but I figure it is better to post here than on the branch that hasn't even got IPCs.
#### Description of issue
IPCs/FBPs tank EMP shots - 90 burn per EMP damages them but they still walk.
PTRS rounds do 80 damage to FBPs and 90 to IPCs when shot in the body. Both can walk.
IEDs knock FBPs down... forever. But they do 5 damage.

(ON PURE BAYCODE) IPC tanked a PTRS round with only forty damage. IPC took ZERO DAMAGE from an EMP grenade.  FBP human took 90 burn from EMP. FBP human took 90 brute from PTRS round. Could walk away after knockdown.
#### Difference between expected and actual behavior
EMP should instakill them tbh. PTRS rounds should come pretty close, but I'm not sure how you can fix that part.
IEDs should do more damage and less knockdown.
Shit's OP yo.
#### Steps to reproduce 
Make IPC/FBP human.
Attack them with an EMP, PTRS round, or IED.

#### Server revision & Game ID

ID: bM5-aWbk

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by andersonconagher** [comment]
Looks like internal organs are straight up immune to EMPs now. https://github.com/Baystation12/Baystation12/issues/15588

Bonus: IPCs cannot be flashed. FBPs can.

**Comment by scrdest** [comment]
Bay issue. No point doubling the work. IPCs are functionally axed as a player race anyway.
