### ISSUE TITLE
IPCs eat their limbs instead of putting them back on.

### ISSUE THREAD

**Issue by andersonconagher** [scrdest/UristMcStation#52]
#### Description of issue
Title. 
Also, their limbs taste like protein.
(IPCs can also vomit, but no big deal)
#### Difference between expected and actual behavior
They should probably put their limbs back on instead of shoving them into their nonexistent mouths.

This happens on pure baycode as well as this code here. For some reason Bay has not reported this, so maybe I'm doing it wrong.

#### Steps to reproduce 
Remove hand. Click self with hand. "Do you really want to use this organ as food? Ew, no/Bon appetit!"

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by andersonconagher** [comment]
It turns out, IPCs can eat and drink. Bread, their hands, whatever's food I guess.

**Comment by scrdest** [comment]
This is not an IPC issue. All species do that, biting organs just got changed not to require the mouth-target bite. Plus, IPCs are kill unless you specifically spawn/modify yourself to be one.

It appears that IPC limbs are *not* robolimbs but their own distinct organ - that would be why you cannot reattach them like robolimbs but require surgery as usual. They would be hilariously imbalanced if they *could* just slap 'em back on, anyway.
