### ISSUE TITLE
Instant cloning

### ISSUE THREAD

**Issue by Naxodile** [scrdest/UristMcStation#55]
#### Description of issue
Due to set/get/adjustCloneLoss as well as set/get/adjustBrainLoss returning 
instantly clones are made instantly without any genetic damage or brain damage.

#### Difference between expected and actual behavior
Cloning is instant instead of taking time.

#### Steps to reproduce 
Attempt to clone anything.

#### Specific information for locating
/code/modules/mob/living/living.dm
/code/modules/organs/organ_damage.dm has the new proc calls for changing clone damage.
/code/game/machinery/cloning.dm
#### Length of time in which bug has been known to occur
N/A

#### Server revision & Game ID
N/A

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this]

**Comment by scrdest** [comment]
I do not follow what them returning instantly has to do with cloning time.

**Comment by Naxodile** [comment]
Perhaps instantly wasn't the right word.
Here's the part from machinery/cloning.dm that does cloning damage 
H.setCloneLoss(H.maxHealth * (100 - config.health_threshold_crit) / 100)
and here's setCloneLoss from living.dm
/mob/living/proc/setCloneLoss(var/amount)
	return
https://github.com/scrdest/UristMcStation/blob/July2016Merge/code/modules/mob/living/living.dm#L274
https://github.com/scrdest/UristMcStation/blob/July2016Merge/code/game/machinery/cloning.dm#L130

**Comment by scrdest** [comment]
You, uh, you've been looking at the wrong file. The mob created is, of course, /living/carbon/human, not just mob/living. It overrides these procs. 

The human ones might be buggy, but I think just from looking at the cloning code that fully-grown clones are supposed to be healthy. If they do get made instantly, that's caused by something else.
